name: chathub
description: "A Chatting App Developed by Rilon"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #firebase
  firebase_analytics: ^11.4.4
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.6.5
  # google_sign_in: ^6.1.6
  firebase_auth: ^5.5.1

  # For handling google sign in
  google_sign_in: ^6.2.1

  # For showing network images
  cached_network_image: ^3.3.1

  # For picking images
  image_picker: ^1.1.2

  # For accessing Firebase Storage (for uploading files)
  firebase_storage: ^12.0.0

  # For showing Emojis
  emoji_picker_flutter: ^4.3.0

  # Bearer Token for Push Notification
  googleapis_auth: ^2.0.0

  # For calling RestAPIs
  http: ^1.2.1

  # For creating notification channel
  flutter_notification_channel: ^3.1.0

  # # For storing images into gallery
  # gallery_saver_updated: ^3.0.0

  # For Playing Lottie Animation
  lottie: ^3.1.2

  # Google Gemini Ai Integration
  google_generative_ai: ^0.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
